In [5]:
import torch

In [21]:
# Number
t1 = torch.tensor(1)
t1.dtype

torch.int64

In [22]:
# Float Number 
t2 = torch.tensor(2.0)
t2.dtype

torch.float32

In [23]:
# Vector
t3 = torch.tensor([1, 2, 3.])
t3.dtype

torch.float32

In [24]:
# Matrix
t4 = torch.tensor([[1, 2], [3, 4]])
t4

tensor([[1, 2],
        [3, 4]])

In [25]:
# 3D array
t5 = torch.tensor([
    [[1, 2], [3, 4], [5, 6]],
    [[1, 4], [3, 16], [25, 36]],
])
t5

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 1,  4],
         [ 3, 16],
         [25, 36]]])

In [26]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)
print(t5.shape)

torch.Size([])
torch.Size([])
torch.Size([3])
torch.Size([2, 2])
torch.Size([2, 3, 2])


# Tensor operations and gradients

In [27]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [29]:
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [30]:
# Compute derivates
y.backward()

In [31]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


 # Pytorch and Numpy

In [34]:
import numpy as np

np_array = np.array([[1, 2], [3, 4]])
np_array

array([[1, 2],
       [3, 4]])

In [36]:
np_array_as_tensor = torch.from_numpy(np_array)
np_array_as_tensor

tensor([[1, 2],
        [3, 4]])

In [37]:
print(np_array.dtype)
print(np_array_as_tensor.dtype)

int64
torch.int64
